import React, {ReactNode} from 'react';
import type {Metadata} from 'next';
import getAllBuildings from "@/lib/get-all-buildings";
import buildingsAsGeoJSON from "@/lib/get-all-buildings-geojson";
import MapClientLayout from "@/components/map-client-layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export type MapLayoutProps = {
    readonly sidebar: ReactNode;
}

export default async function MapLayout(props: MapLayoutProps) {
    const {sidebar} = props;
    const buildings = await getAllBuildings();
    const buildingsGeoJSON = buildingsAsGeoJSON(buildings);
    return (
        <MapClientLayout className='h-[calc(100vh-theme(spacing.16))]'
                         buildingsGeoJSON={buildingsGeoJSON}>
            {sidebar}
        </MapClientLayout>
    );
}
